"""The shipped example workflows: internally consistent, and wired to sockets the nodes actually have.

These graphs are generated by ``tools/make_example_workflows.py`` and are the first thing a user loads, so a stale
socket name is a broken first impression. The structural half is stdlib only and always runs; the half that checks
each HyperFlow node against its own ``INPUT_TYPES`` needs ComfyUI.
"""

from __future__ import annotations

import ast
import json
import os
import unittest

from tests.support import ROOT, needs_comfy

WORKFLOWS = os.path.join(ROOT, "example_workflows")
#: Node types the examples borrow from ComfyUI core, plus the one third-party node the lip-sync branch needs.
CORE_NODES = {
    "UNETLoader", "CLIPLoader", "VAELoader", "KSamplerSelect", "RandomNoise", "BasicGuider",
    "SamplerCustomAdvanced", "VAEDecode", "VAEDecodeAudio", "CreateVideo", "SaveVideo", "LoadImage", "LoadAudio",
    "LoadVideo", "GetVideoComponents", "MarkdownNote", "PrimitiveStringMultiline", "MiniMaxH3ImageToVideo",
    "MiniMaxH3ReferenceToVideo", "MiniMaxH3AddGuide",
}
THIRD_PARTY_NODES = {"LatentSyncNode"}  # ComfyUI-LatentSyncWrapper, bypassed by default
#: One graph per task the pack claims to support, so the README table cannot drift from what ships.
EXPECTED = {
    "hyperflow_t2va.json", "hyperflow_fl2va.json", "hyperflow_ref2va.json", "hyperflow_audio2va.json",
    "hyperflow_ref2va_2speaker_dialogue.json", "hyperflow_singularity_multimodal.json",
}
#: Input types ComfyUI draws as a widget rather than a socket (a list is a combo box).
WIDGET_TYPES = {"INT", "FLOAT", "STRING", "BOOLEAN"}


def pack_node_types() -> set[str]:
    """The pack's own node ids, read from the source so this test needs neither torch nor ComfyUI."""
    names = set()
    for source in ("nodes.py", "dialogue_nodes.py"):
        with open(os.path.join(ROOT, source), encoding="utf-8") as handle:
            tree = ast.parse(handle.read())
        for node in ast.walk(tree):
            if not isinstance(node, ast.Assign) or not isinstance(node.value, ast.Dict):
                continue
            if not any(isinstance(t, ast.Name) and t.id == "NODE_CLASS_MAPPINGS" for t in node.targets):
                continue
            names |= {k.value for k in node.value.keys if isinstance(k, ast.Constant)}
    return names


def load(name):
    with open(os.path.join(WORKFLOWS, name), encoding="utf-8") as handle:
        return json.load(handle)


class StructureTest(unittest.TestCase):
    def setUp(self):
        self.files = sorted(f for f in os.listdir(WORKFLOWS) if f.endswith(".json"))
        self.known = pack_node_types() | CORE_NODES | THIRD_PARTY_NODES

    def test_one_graph_per_supported_task(self):
        self.assertEqual(set(self.files), EXPECTED)

    def test_graphs_are_consistent(self):
        for name in self.files:
            with self.subTest(name):
                graph = load(name)
                nodes = {n["id"]: n for n in graph["nodes"]}
                self.assertEqual(len(nodes), len(graph["nodes"]), "duplicate node id")
                ids = [link[0] for link in graph["links"]]
                self.assertEqual(len(set(ids)), len(ids), "duplicate link id")
                self.assertGreaterEqual(graph["last_node_id"], max(nodes))
                # a high-water mark, not a count: a graph may delete a link and must never reissue its id
                self.assertGreaterEqual(graph["last_link_id"], max(ids))

                for node in graph["nodes"]:
                    self.assertIn(node["mode"], (0, 4), f"node {node['id']} has mode {node['mode']}")
                    self.assertIn(node["type"], self.known, f"unknown node type {node['type']}")

                for lid, src, sslot, dst, dslot, kind in graph["links"]:
                    self.assertIn(src, nodes, f"link {lid} from a missing node")
                    self.assertIn(dst, nodes, f"link {lid} to a missing node")
                    outputs, inputs = nodes[src]["outputs"], nodes[dst]["inputs"]
                    self.assertLess(sslot, len(outputs), f"link {lid}: node {src} has no output {sslot}")
                    self.assertLess(dslot, len(inputs), f"link {lid}: node {dst} has no input {dslot}")
                    self.assertEqual(outputs[sslot]["type"], kind, f"link {lid} type vs output type")
                    self.assertEqual(inputs[dslot]["type"], kind, f"link {lid} type vs input type")
                    self.assertIn(lid, outputs[sslot]["links"], f"link {lid} missing from its output")
                    self.assertEqual(inputs[dslot]["link"], lid, f"link {lid} not recorded on its input")

                known_links = set(ids)
                for node in graph["nodes"]:
                    for slot in node["inputs"]:
                        if slot["link"] is not None:
                            self.assertIn(slot["link"], known_links, f"node {node['id']} input {slot['name']}")
                    for slot in node["outputs"]:
                        for lid in slot["links"]:
                            self.assertIn(lid, known_links, f"node {node['id']} output {slot['name']}")

    def test_every_graph_loads_hyperflow_once_and_samples_its_grid(self):
        """The guarantees the README states: one loader, HyperFlow's own sigmas, euler, cfg 1.0 (BasicGuider)."""
        for name in self.files:
            with self.subTest(name):
                graph = load(name)
                types = [n["type"] for n in graph["nodes"] if n["mode"] == 0]
                self.assertEqual(types.count("HyperFlowLoRALoader"), 1)
                self.assertEqual(types.count("HyperFlowSigmas"), 1)
                self.assertEqual(types.count("BasicGuider"), 1)
                sampler = next(n for n in graph["nodes"] if n["type"] == "KSamplerSelect")
                self.assertEqual(sampler["widgets_values"][0], "euler")

    def test_audio_driven_graphs_derive_their_length_from_the_audio(self):
        """An audio-driven render must not sit at the 124-frame default while the track runs longer."""
        for name in ("hyperflow_audio2va.json", "hyperflow_ref2va.json"):
            with self.subTest(name):
                graph = load(name)
                measure = next(n for n in graph["nodes"] if n["type"] == "HyperFlowAudioLength")
                length_slot = measure["outputs"][1]
                self.assertEqual(length_slot["name"], "length")
                self.assertTrue(length_slot["links"], "'length' is measured but not wired to anything")
                targets = {link[3] for link in graph["links"] if link[0] in length_slot["links"]}
                for target in targets:
                    node = next(n for n in graph["nodes"] if n["id"] == target)
                    slot = next(s for s in node["inputs"] if s["link"] in length_slot["links"])
                    self.assertEqual(slot["name"], "length")
                    self.assertEqual(slot.get("widget", {}).get("name"), "length", "not a widget-converted input")


@needs_comfy
class SocketTest(unittest.TestCase):
    """Each HyperFlow node in the examples against its own INPUT_TYPES, so an upstream rename is caught here."""

    @classmethod
    def setUpClass(cls):
        from tests.test_comfy import _load_nodes

        cls.classes = _load_nodes().NODE_CLASS_MAPPINGS

    def test_hyperflow_sockets_and_widgets_match(self):
        for name in sorted(f for f in os.listdir(WORKFLOWS) if f.endswith(".json")):
            graph = load(name)
            for node in graph["nodes"]:
                cls = self.classes.get(node["type"])
                if cls is None:
                    continue
                spec = cls.INPUT_TYPES()
                declared = {**spec.get("required", {}), **spec.get("optional", {})}
                with self.subTest(workflow=name, node=node["type"], id=node["id"]):
                    for slot in node["inputs"]:
                        self.assertIn(slot["name"], declared, "input socket this node does not have")
                    widgets = [n for n, s in declared.items() if _is_widget(s)]
                    self.assertEqual(len(node["widgets_values"]), len(widgets),
                                     f"widget values {node['widgets_values']} vs widgets {widgets}")
                    required = spec.get("required", {})
                    linked = {s["name"] for s in node["inputs"] if s["link"] is not None}
                    for input_name, input_spec in required.items():
                        if not _is_widget(input_spec):
                            self.assertIn(input_name, linked, "required socket is not connected")


def _is_widget(spec) -> bool:
    kind, options = (spec[0], spec[1] if len(spec) > 1 else {}) if isinstance(spec, tuple) else (spec, {})
    if options.get("forceInput"):
        return False  # drawn as a socket even though its type is a widget type
    return isinstance(kind, list) or kind in WIDGET_TYPES


if __name__ == "__main__":
    unittest.main()
